require("lorenzo.plugins.telescope")
require("lorenzo.plugins.colorscheme")
require("lorenzo.plugins.treesitter")
require("lorenzo.plugins.lualine")
require("lorenzo.plugins.lsp")
require("lorenzo.plugins.vimtex")
